apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "ebot7-service.fullname" . }}
  labels:
    {{- include "ebot7-service.labels" . | nindent 4 }}
spec:
  parameters:
    objects: |
      {{- range .Values.awsSecrets }}
      - objectAlias: {{ .objectAlias }}
        objectType: secretsmanager
        objectName: {{ .objectName }}
      {{- end }}
      
  provider: aws
  secretObjects:
    - data:
       {{- range .Values.awsSecrets }}
        - key: {{ .objectAlias }}
          objectName: {{ .objectAlias }}
        {{- end }}
      secretName: {{ include "ebot7-service.fullname" . }}-aws
      type: Opaque
